---
ruby_version: 2.6.0
deploy_user: deployer
app_name: application
deploy_path: '/apps'
app_env: staging

databases:
  - { db_name: '{{ app_name }}_production',  db_user: 'production_user',  db_password: 'production_pass' }
  - { db_name: '{{ app_name }}_staging',     db_user: 'staging_user',     db_password: 'staging_pass' }
  - { db_name: '{{ app_name }}_development', db_user: 'development_user', db_password: 'development_pass' }
  - { db_name: '{{ app_name }}_test',        db_user: 'development_user', db_password: 'development_pass' }

postgres_data_dir: /data/postgres
postgres_listen_address: '*'
postgres_port: 5432

## Tune: mem_24_cpu_16_con_600_store_ssd ________________
#postgres_max_connections: 600
#postgres_shared_buffers: 6GB
#postgres_effective_cache_size: 18GB
#postgres_maintenance_work_mem: 1536MB
#postgres_checkpoint_completion_target: 0.7
#postgres_wal_buffers: 16MB
#postgres_default_statistics_target: 100
#postgres_random_page_cost: 1.1
#postgres_effective_io_concurrency: 200
#postgres_work_mem: 1310kB
#postgres_min_wal_size: 1GB
#postgres_max_wal_size: 2GB
#postgres_max_worker_processes: 16
#postgres_max_parallel_workers_per_gather: 8
#postgres_max_parallel_workers: 16

## Tune: mem_8_cpu_4_con_200_store_ssd ________________
#postgres_max_connections: 200
#postgres_shared_buffers: 2GB
#postgres_effective_cache_size: 6GB
#postgres_maintenance_work_mem: 512MB
#postgres_checkpoint_completion_target: 0.7
#postgres_wal_buffers: 16MB
#postgres_default_statistics_target: 100
#postgres_random_page_cost: 1.1
#postgres_effective_io_concurrency: 200
#postgres_work_mem: 5242kB
#postgres_min_wal_size: 1GB
#postgres_max_wal_size: 2GB
#postgres_max_worker_processes: 4
#postgres_max_parallel_workers_per_gather: 2
#postgres_max_parallel_workers: 4

## Tune: mem_4_cpu_2_con_50_store_ssd ________________
postgres_max_connections: 50
postgres_shared_buffers: 1GB
postgres_effective_cache_size: 3GB
postgres_maintenance_work_mem: 256MB
postgres_checkpoint_completion_target: 0.7
postgres_wal_buffers: 16MB
postgres_default_statistics_target: 100
postgres_random_page_cost: 1.1
postgres_effective_io_concurrency: 200
postgres_work_mem: 20971kB
postgres_min_wal_size: 1GB
postgres_max_wal_size: 2GB
postgres_max_worker_processes: 2
postgres_max_parallel_workers_per_gather: 1
postgres_max_parallel_workers: 2