---
- name: Ensure user {{ item.db_user }} exists
  postgresql_user:
    name: '{{ item.db_user }}'
    password: '{{ item.db_password }}'
    state: present
    encrypted: true
    login_user: postgres
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true

- name: Ensure database {{ item.db_name }} exists
  postgresql_db:
    name: '{{ item.db_name }}'
    state: present
    owner: '{{ item.db_user }}'
    encoding: UTF-8
    template: template0
    login_user: postgres
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
