---
- include_tasks: '{{ ansible_os_family }}/init_db.yml'

- include_tasks: '{{ ansible_os_family }}/update_config.yml'

- include_tasks: RedHat/enable_service.yml
  when: ansible_os_family == 'RedHat'
