---
- include_tasks: '{{ ansible_os_family }}/add_repo.yml'

- include_tasks: '{{ ansible_os_family }}/install_postgres.yml'

- include_tasks: initialize.yml

- include_tasks:  '{{ ansible_os_family }}/start_service.yml'

- include_tasks: create_db.yml
  notify:
    - restart postgres
  with_items:
    - '{{ databases }}'
