---
- name: Add nginx repo
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
  become: true

- import_task: apt/install_nginx.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_task: yum/install_nginx.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Ensure configuration directorie exists
  file:
    path: '{{ item }}'
    state: directory
  become: true
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/nginx/sites-available

- name: Upload default confing
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify:
    - restart nginx
