---
- name: Add nginx repo
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
  become: true

- name: Install nginx YUM
  yum:
    name: '{{ item }}'
    state: installed
    update_cache: yes
  with_items:
    - nginx
  become: true

- name: Ensure configuration directorie exists
  file:
    path: '{{ item }}'
    state: directory
  become: true
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/nginx/sites-available

- name: Upload default confing
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify:
    - restart nginx
