---
- name: Install dependencies YUM
  yum:
    name: '{{ item }}'
    state: installed
    update_cache: yes
  with_items:
    - git
    - gcc
    - bzip2
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
  become: true
