---
- name: Initial provisioning
  hosts: all
  strategy: free
  gather_facts: no

  roles:
    - setup

- name: Provision Web server
  hosts: web
  strategy: free

  roles:
    - rails
    - nginx
    - rbenv

- name: Provision DB server
  hosts: db
  strategy: free

  roles:
    - postgresql
