---
- name: Initial setup
  hosts: all
  gather_facts: no

  roles:
    - setup

- name: Configure Web server
  hosts: web

  roles:
    - rails-config
    - nginx
    - rbenv

- name: Configure DB server
  hosts: db

  roles:
    - postgres
