---
- name: Initial setup
  hosts: all
  strategy: free
  gather_facts: no

  roles:
    - setup

- name: Configure Web server
  hosts: web
  strategy: free

  roles:
    - rails-config
    - nginx
    - rbenv

- name: Configure DB server
  hosts: db
  strategy: free

  roles:
    - postgres
