---
- name: Install application specific dependencies
  apt:
    name: '{{ item }}'
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - libmysqlclient-dev
    - imagemagick
  become: true

- name: Add nodejs ppa Debian
  get_url: 
    url: https://deb.nodesource.com/setup_8.x
    dest: /tmp/nodejs.sh

- name: Execute nodejs ppa
  script: /tmp/nodejs.sh

- name: Install nodejs APT
  apt:
    name: nodejs 
    state: installed 
    force: yes 
    update_cache: yes
    cache_valid_time: 3600
  become: true
