---
- name: Create deployment user
  user:
    name: '{{ deploy_user }}'
    comment: "Application deployment user"
  become: true

- name: Update user permissions at /etc/sudoers.d/{{ deploy_user }}
  template:
    src: templates/sudoer.j2
    dest: /etc/sudoers.d/{{ deploy_user }}
    owner: root
    group: root
    mode: 0440
  become: true

- name: Create deploy path {{ deploy_path }}
  file:
    path: '{{ deploy_path }}'
    state: directory
    group: '{{ deploy_user }}'
    owner: '{{ deploy_user }}'
  become: true

- name: Create .ssh folder
  file:
    path: '/home/{{ deploy_user }}/.ssh'
    state: directory
    group: '{{ deploy_user }}'
    owner: '{{ deploy_user }}'
  become: true

- name: "Update {{ deploy_user }}'s allowed keys"
  copy:
    remote_src: true
    src: /home/{{ ansible_user }}/.ssh/authorized_keys
    dest: /home/{{ deploy_user }}/.ssh/authorized_keys
    group: '{{ deploy_user }}'
    owner: '{{ deploy_user }}'
  become: true

- include_tasks: '{{ ansible_os_family }}/install_node.yml'

- include_tasks: '{{ ansible_os_family }}/install_deps.yml'
