---
- name: Update pg_hba config {{ ansible_os_family }}
  template:
    src: pg_hba.conf.j2
    dest: '{{ item }}'
    group: postgres
    owner: postgres
  become: true
  with_items:
    - '{{ postgres_data_dir }}/pg_hba.conf'
    - /var/lib/pgsql/11/data/pg_hba.conf

- name: Update postgres config {{ ansible_os_family }}
  template:
    src: postgresql.conf.j2
    dest: '{{ item }}'
    group: postgres
    owner: postgres
  become: true
  with_items:
    - '{{ postgres_data_dir }}/postgresql.conf'
    - /var/lib/pgsql/11/data/postgresql.conf

- name: Update postgres service
  raw: sed 's|/var/lib/pgsql/11/data/|{{ postgres_data_dir }}/|g' -i /usr/lib/systemd/system/postgresql-11.service && systemctl daemon-reload
  become: true
  notify: restart postgres rhel