---
- name: restart postgres rhel
  service:
    name: postgresql-10
    state: restarted
    enabled: yes
  become: true
  when: ansible_os_family == 'RedHat'

- name: start postgres rhel
  service:
    name: postgresql-10
    state: started
    enabled: yes
  become: true
  when: ansible_os_family == 'RedHat'

- name: restart postgres debian
  service:
    name: postgresql
    state: restarted
    enabled: yes
  become: true
  when: ansible_os_family == 'Debian'

- name: start postgres debian
  service:
    name: postgresql
    state: started
    enabled: yes
  become: true
  when: ansible_os_family == 'Debian'
