---
- name: Install dependencies {{ ansible_os_family }}
  apt:
    name:
      - git
      - autoconf
      - bison
      - build-essential
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm3
      - libgdbm-dev
    state: present
    update_cache: yes
  become: true
