---
- name: Check if postgres data-dir is initialized
  find: 
    paths: /var/lib/pgsql/10/data
    file_type: directory
    patterns: "*"
  register: psql_data
  become: true
  ignore_errors: yes

- name: Initialize postgres data-dir
  raw: /usr/pgsql-10/bin/postgresql-10-setup initdb
  become: true
  ignore_errors: true
  when: psql_data.matched|int == 0