---
- name: Install postgresql 11 {{ ansible_os_family }}
  yum:
    name:
      - postgresql11-server
      - postgresql11-libs
      - postgresql11-devel
      - postgresql11-contrib
      - python-psycopg2
    state: present
    update_cache: true
  become: true
