---
- name: Update pg_hba config {{ ansible_os_family }}
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/10/data/pg_hba.conf
  become: true

- name: Update postgres config {{ ansible_os_family }}
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/10/data/postgresql.conf
  become: true
