---
- name: Install postgresql 10 {{ ansible_os_family }}
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python-psycopg2
    state: present
    update_cache: true
  become: true
