---
- name: Update apt cache
  raw: apt-get -y update
  become: true

- name: Upgrade packages
  raw: apt-get -y dist-upgrade
  become: true

- name: Cleanup apt
  raw: apt-get -y autoremove && apt-get -y clean
  become: true

- name: Install python2 for xenial
  raw: apt-get install -y --force-yes python-simplejson
  when: release.stdout == 'xenial'
  become: true
