---
- name: Determine distribution Debian
  raw: lsb_release -a 2>/dev/null | grep Codename | awk '{printf("%s"), $2}'
  register: release
  ignore_errors: yes

- name: Determine distribution RHEL
  raw: cat /etc/os-release | grep "ID=" | head -1 | tr '"' ' ' | awk '{gsub("ID=","",$NF); printf("%s"), $NF}'
  register: release
  ignore_errors: yes

- debug:
    var: release.stdout

- block:
  - name: Update yum cache
    raw: yum -y update
    become: true

  - name: Upgrade yum packages
    raw: yum -y upgrade
    become: true

  - name: Cleanup yum
    raw: yum -y clean packages
    become: true

  when: release.stdout == 'centos'

- block:
  - name: Enable EPEL
    raw: '{{ item }}'
    become: true
    with_items:
      - 'rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
      - 'yum-config-manager --enable epel'
    ignore_errors: yes

  - name: Update yum cache
    raw: yum -y update
    become: true

  - name: Upgrade yum packages
    raw: yum -y upgrade
    become: true

  - name: Cleanup yum
    raw: yum -y clean packages
    become: true

  when: release.stdout == 'rhel'

- block:
  - name: Update apt cache
    raw: apt-get -y update
    become: true

  - name: Upgrade apt packages
    raw: apt-get -y upgrade
    become: true

  - name: Install ansible dependency
    raw: apt-get install -y python-simplejson
    become: true

  - name: Cleanup apt
    raw: apt-get -y autoremove && apt-get -y clean
    become: true

  when: release.stdout == 'ubuntu'
