- name: Create deployment user
  user: name={{ deploy_user }} comment="Application deployment user"
  become: true

# - name: Create deployment directory
#   file: >
#     path={{deploy_directory}} 
#     owner={{ deploy_user }}
#     group={{ deploy_user }}
#     state=directory
#   become: true

- name: Update user permissions
  template:
    src: templates/deployer.j2
    dest: /etc/sudoers.d/deployer
    owner: root
    group: root
    mode: 0440
  become: true

- name: Create .ssh folder
  file:
    path: '/home/{{ deploy_user }}/.ssh'
    state: directory
    group: '{{ deploy_user }}'
    owner: '{{ deploy_user }}'
  become: true

- name: "Update {{ deploy_user }}'s allowed keys"
  copy:
    remote_src: true
    src: /home/{{ remote_user }}/.ssh/authorized_keys
    dest: /home/{{ deploy_user }}/.ssh/authorized_keys
    group: '{{ deploy_user }}'
    owner: '{{ deploy_user }}'
  become: true

- include-tasks: distros/apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include-tasks: distros/yum.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'
