---
- include_tasks: '{{ ansible_os_family }}/install-deps.yml'

- name: Install rbenv
  include_tasks: install-rbenv.yml

- name: Install pluginns
  include_tasks: plugins/{{ item }}.yml
  with_items:
    - ruby-build
    - rbenv-default-gems

- name: Install ruby
  include_tasks: install-ruby.yml

- name: Make sure bundler is installed
  raw: 'RBENV_ROOT={{ rbenv_path }} RBENV_VERSION={{ ruby_version }} {{ rbenv_path }}/bin/rbenv exec gem install bundler'
  become: true

- name: Update folder permissionos
  file:
    dest: '{{ rbenv_path }}'
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user }}'
    mode: 0775
    recurse: true
  become: true
