---
- name: Install debian dependencies
  import_tasks: dependencies/apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install RHEL dependencies
  import_tasks: dependencies/yum.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install rbenv
  import_tasks: install-rbenv.yml

- name: Install ruby-build
  import_tasks: plugins/ruby-build.yml

- name: Install rbenv-default-gems
  import_tasks: plugins/rbenv-default-gems.yml

- name: Install ruby
  import_tasks: install-ruby.yml

- name: Make sure bundler is installed
  raw: 'RBENV_ROOT={{ rbenv_path }} RBENV_VERSION={{ ruby_version }} {{ rbenv_path }}/bin/rbenv exec gem install bundler'
  become: true
