---
- import_tasks: yum/add_repo.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: apt/add_repo.yml
  when: ansible_os_family == 'Debian'

- import_tasks: yum/install_postgres.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: apt/install_postgres.yml
  when: ansible_os_family == 'Debian'

- import_tasks: yum/init_db.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: yum/enable_service.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: yum/start_service.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: apt/start_service.yml
  when: ansible_os_family == 'Debian'

- import_tasks: yum/update_config.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: apt/update_config.yml
  when: ansible_os_family == 'Debian'

- include_tasks: create_db.yml
  notify:
    - restart postgres
  with_items:
    - '{{ databases }}'
